import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/style/globals.css";
import GoogleAnalytics from "@/components/GoogleAnalytics/GoogleAnalytics";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <head>
                <Suspense>
                    <GoogleAnalytics />
                </Suspense>
            </head>
            <body className={inter.className}>{children}</body>
        </html>
    );
}
