import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/style/globals.css";
import GoogleAnalytics from "@/components/GoogleAnalytics/GoogleAnalytics";
import { Suspense } from "react";
import { AuthProvider } from "@/context/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthProvider>
            <html lang="ja">
                <head>
                    <Suspense>
                        <GoogleAnalytics />
                    </Suspense>
                </head>
                <body className={inter.className}>
                    <main className="flex min-h-screen flex-col items-center justify-between p-24">
                        {children}
                    </main>
                </body>
            </html>
        </AuthProvider>
    );
}
